---
title: "Publications"
output: html_document
---

<style>
.text.extra-padding {
    padding-left: 100px; 
    max-width:100%;
  }
</style>
<br>
<br>
**Publications** 
<br>
<div class="text extra-padding"> 
Meryem Ayşe Yücel, Robert Luke, Rickson Coelho Mesquita, … **Michaela Kent**, … Vit Zemanek (preprint). [The fNIRS Reproducibility Study Hub (FRESH): Exploring Variability and Enhancing Transparency in fNIRS Neuroimaging Research](https://osf.io/preprints/metaarxiv/pc6x8).
<br>
[Preprint](https://osf.io/preprints/metaarxiv/pc6x8)
<br>
<br>
Homa Vahidi, Alexandra Kowalczyk, Kevin Stubbs, Melab Musabi, Sriya Roychaudhuri, **Michaela Kent**, Soume Bhattacharya, Sandrine de Ribaupierre, Keith St. Lawrence, Yalda Mohsenzadeh & Emma Duerden (2024, *in press*). [Investigating Task-Free Functional Connectivity Patterns in Newborns Using functional Near-Infrared Spectroscopy](https://www.biorxiv.org/content/10.1101/2023.09.05.555980v1). *Brain and Behavior*.
<br>
[Preprint](https://www.biorxiv.org/content/10.1101/2023.09.05.555980v1) 
</div>
<div class="text extra-padding"> 
Ruud Hortensius* , **Michaela Kent*** , Kohinoor M. Darda, Laura Jastrzab, Kami Koldewyn, Richard Ramsey & Emily S. Cross (2021). [Exploring the relationship between anthropomorphism and theory-of-mind in brain and behaviour](https://onlinelibrary.wiley.com/doi/epdf/10.1002/hbm.25542). *Human Brain Mapping*.
<br>
* These authors contributed equally
<br>
[Full Text](https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.25542) | [Preprint](https://psyarxiv.com/3uj4g/) | [Preregistration](https://osf.io/tuq4a) | [Data](https://osf.io/rg5kn/) | [NeuroVault](https://neurovault.org/collections/6615/) | [Code](https://gitlab.com/hortensius/anthrom)
<br>
<br>
Anna Henschel, **Michaela Kent**, Luca M. Leisten, Hanna Seelemeyer, Rosanne Timmerman, Ruud Hortensius & Emily S. Cross (2020). [A manual to digitising fNIRS probes with photogrammetry as described in Clausner et. al. (2017)](https://zenodo.org/record/4146985). *Zenodo*.
<br>
[Zenodo](https://zenodo.org/record/4146985) | [PDF](https://www.soba-lab.com/_files/ugd/3e5863_cf150f119e2640d1a0c6963ea7fc20f4.pdf) 
<br>
<br>
</div>
**Book Chapter** 
<br>
<div class="text extra-padding"> 
**Michaela Kent**, Diane Seguin & Emma G. Duerden (in press). Technology-based learning tools and face processing in children with Autism Spectrum Disorder. *Handbook of Neural Engineering, Volume 5: Small Vessel Diseases of Brain*.
<br>
<br>
</div>
**Science Communication** 
<br>
<div class="text extra-padding"> 
**Michaela Kent** & Emma G. Duerden (2024). [Excessive social media use during the COVID-19 pandemic exacerbated adolescent mental health challenges.](https://theconversation.com/excessive-social-media-use-during-the-covid-19-pandemic-exacerbated-adolescent-mental-health-challenges-217986) *The Conversation*.
<br>
<br>
**Michaela Kent** (2023). [How do brain structure differences affect reading abilities?](https://songsuwo.ca/thedorsalcolumn/vol-4-iss-4-michaela-kent) *The Dorsal Column*.
<br>
<br>
**Michaela Kent** (2023). [The Promise of Bedside Brain Imaging in Babies.](https://songsuwo.ca/thedorsalcolumn/vol4-iss2-michaela-kent) *The Dorsal Column*.
<br>
<br>
**Michaela Kent** (2022). [The amygdala, anxiety and Autism Spectrum Disorder.](https://songsuwo.ca/thedorsalcolumn/vol3-iss4-michaela-kent) *The Dorsal Column*.
<br>
<br>
**Michaela Kent** (2022). [The Damaging Effects of Orphanages on the Brain.](https://songsuwo.ca/thedorsalcolumn/vol3-iss2-michaela-kent) *The Dorsal Column*.
<br>
<br>
</div>
**Presentations** 
<div class="text extra-padding"> 
**Michaela Kent**, Caroline Kelsey, Emma G. Duerden, Jody C. Culham, Michelle Bosquet Enlow & Charles A. Nelson (2024, Jul). Neural correlates of face processing are associated with Theory of Mind development in early childhood. Oral presentation at the International Congress of Infant Studies, Glasgow, U.K.
<br>
<br>
**Michaela Kent** (2023, Oct). Exploring the neural correlates of face processing and Theory of Mind in early development. Oral presentation at WestNIRS, London, ON, Canada.
<br>
<br>
**Michaela Kent** (2022, Sep). Evaluating the importance of animacy and visual realism in social interactions using fNIRS. Oral presentation at WestNIRS, London, ON, Canada.
<br>
<br>
**Michaela Kent**(2021, Nov). Introduction to functional Near-Infrared Spectroscopy. Tutorial and presentation at Brainhack, London, ON, Canada.
<br>
<br>
</div>
**Poster Presentations** 
<div class="text extra-padding"> 
Brian Krivoruk, Homa Vahidi, **Michaela Kent** & Emma G. Duerden (2024, Oct). Social Media Screen Time Use and Brain Connectivity in Adolescents. Poster presentation at the Society for Neuroscience, Chicago, USA.
<br>
<br>
**Michaela Kent**, Homa Vahidi, Brian Krivoruk & Emma G. Duerden (2024, Sep). The social brain network and adolescent screen time. Poster presentation at the Society for fNIRS, Birmingham, U.K.
<br>
<br>
**Michaela Kent**, Kevin Stubbs, Homa Vahidi & Jody C. Culham (2024, Sep). Two Human Datasets Reveal the Benefits of Event-Related Designs and Deconvolution for fNIRS Research. Poster presentation at the Society for fNIRS, Birmingham, U.K.
<br>
<br>
Lauren M. MacIntyre, **Michaela Kent**, Brian Krivoruk, Eun Jung Choi & Emma G. Duerden (2024, Mar). Media Screen Time Use in Adolescents and the Association with the Social Brain Network: fNIRS Study. Poster presentation at Inspiring Diversity in STEM, London, ON, Canada.
<br>
<br>
**Michaela Kent*** , Eva Deligiannis* , Karsten Babin, Kevin Stubbs, Emma G. Duerden & Jody C. Culham (2023, Nov). Exploring how evoked-responses to social interactions are influenced by animacy and visual realism in online environments using fNIRS. Poster presentation at the Society for Neuroscience, Washington DC, USA.
<br>
<br>
Homa Vahidi, Alexandra Kowalczyk, Kevin Stubbs, Melab Musabi, Sriya Roychaudhuri, **Michaela Kent**, Soume Bhattacharya, Sandrine de Ribaupierre, Keith St Lawrence, Yalda Mohsenzadeh & Emma G. Duerden (2023, Nov). Investigating task-free functional connectivity patterns in newborn infants. Poster presentation at the Society for Neuroscience, Washington DC, USA.  
<br>
Eva Deligiannis* , **Michaela Kent*** , Karsten Babin, Kevin Stubbs, Emma G. Duerden & Jody C. Culham (2023, Oct). Can avatars replace us? Poster presentation at WestNIRS, London, ON, Canada.
<br>
<br>
**Michaela Kent*** , Eva Deligiannis* , Karsten Babin, Kevin Stubbs, Emma G. Duerden & Jody C. Culham (2023, Aug). Exploring whether evoked-responses are influenced by animacy and visual realism during virtual social interactions using fNIRS. Poster presentation at the Neuroscience of the Everyday World conference, Boston, MA, USA.
<br>
<br>
Homa Vahidi, Alexandra Kowalczyk, Kevin Stubbs, Melab Musabi, Sriya Roychaudhuri, **Michaela Kent**, Soume Bhattacharya, Sandrine de Ribaupierre, Keith St Lawrence, Yalda Mohsenzadeh & Emma G. Duerden (2022, Nov). Spontaneous Functional Connectivity Increased with Gestational Age: A Functional Near-Infrared Spectroscopy Study in Healthy Newborns. Poster presentation at the Society for Neuroscience conference, San Diego, CA, USA.  
<br>
**Michaela Kent*** , Eva Deligiannis* , Karsten Babin, Kevin Stubbs, Emma G. Duerden & Jody C. Culham (2022, Oct). Evaluating the importance of animacy and visual realism in social interactions using fNIRS. Poster presentation at the Society for fNIRS conference, Boston, MA, USA.
<br>
<br>
**Michaela Kent*** , Eva Deligiannis* , Karsten Babin, Kevin Stubbs, Emma G. Duerden & Jody C. Culham (2022, Sep). Evaluating the importance of animacy and visual realism in social interactions using fNIRS. Poster presentation at the WestNIRS conference, London, ON, Canada.
<br>
<br>
* These authors contributed equally
</div>
